# Generated by Django 3.0.7 on 2020-06-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
