# Generated by Django 3.0.7 on 2020-06-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='status',
        ),
    ]
